import localFont from "next/font/local";
import "./globals.css";

const safiro = localFont({
  src: "./fonts/safiro-medium.otf",
  variable: "--font-safiro-sans",
  weight: "500",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${safiro.variable}  antialiased`}>{children}</body>
    </html>
  );
}
